alarm_arm:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm
    mode:
      required: false
      example: away
      selector:
        select:
          mode: dropdown
          custom_value: true
          translation_key: mode
          options:
            - home
            - away
            - night

alarm_disarm:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm

alarm_trigger:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm
    mode:
      required: false
      example: away
      selector:
        select:
          mode: dropdown
          custom_value: true
          translation_key: mode
          options:
            - home
            - away
            - night

alarm_clear:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm

panic_trigger:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Panic Button

panic_clear:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Panic Button
