arm:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm
    mode:
      required: false
      example: away
      selector:
        text:

disarm:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm

trigger:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm
    mode:
      required: false
      example: away
      selector:
        text:

clear:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Alarm

panic:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Panic Button

panic_clear:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: openalarm
              model: Panic Button
